validate kvdb key value for storing workflowid

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -449,25 +449,29 @@ jobs:
       - run:
           name: Save old workflow id to kvdb.io
           command: |
-            # # export OLD_WORKFLOW_ID=$(aws cloudformation \
-            # #             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-            # #             --no-paginate --output text)
-            # export OLD_WORKFLOW_ID=$(aws cloudformation \
-            #     list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-            #     --no-paginate --output text)
-            # echo "Old Work flow ID: $OLD_WORKFLOW_ID"
-            # curl -d "${OLD_WORKFLOW_ID}" https://kvdb.io/${KVDB_BUKET}/old_workflow_id
-            # # ${CIRCLE_WORKFLOW_ID:0:7}
-              export OLD_WORKFLOW_ID=$(aws cloudformation \
-                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                --no-paginate --output text)
-              echo "list-exports command output: $OLD_WORKFLOW_ID"
-              if [ -z "$OLD_WORKFLOW_ID" ]; then
-                  echo "ERROR: No value returned for WorkflowID export"
-              else
+                  set -x
+                  OLD_WORKFLOW_ID=$(aws cloudformation \
+                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                      --no-paginate --output text)
                   echo "Old workflow ID: $OLD_WORKFLOW_ID"
-                  curl -d "${OLD_WORKFLOW_ID}" https://kvdb.io/${KVDB_BUKET}/old_workflow_id
-              fi
+                  
+                  if [ -z "$OLD_WORKFLOW_ID" ]; then
+                    echo "Error: OLD_WORKFLOW_ID is empty"
+                    exit 1
+                  fi
+                  
+                  # Check if the key already exists
+                  RESPONSE=$(curl -I https://kvdb.io/${KVDB_BUKET}/old_workflow_id 2>/dev/null | head -n 1 | cut -d$' ' -f2)
+                  
+                  # If key exists, update its value
+                  if [[ $RESPONSE -eq 200 ]]; then
+                      curl -X PUT -d "${OLD_WORKFLOW_ID}" https://kvdb.io/${KVDB_BUKET}/old_workflow_id
+                      echo "Value updated in kvdb.io: ${OLD_WORKFLOW_ID}"
+                  # If key does not exist, create it with the value
+                  else
+                      curl -d "${OLD_WORKFLOW_ID}" https://kvdb.io/${KVDB_BUKET}/old_workflow_id
+                      echo "Value saved to kvdb.io: ${OLD_WORKFLOW_ID}"
+                  fi
       - run:
           name: Update cloudfront distribution
           command: |
