asd

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -273,14 +273,22 @@ jobs:
             npm run migrations > migrations_dump.txt
       - run:
           name: Check migration results
+          # command: |
+          #   if [ $? -eq 0 ] && grep -q "Schema successfully updated" ~/project/backend/migrations_dump.txt; then
+          #     echo "Migration was successful and schema was updated"
+          #   else
+          #     echo "Migration failed or schema was not updated"
+          #     echo "Reasons:"
+          #     cat ~/project/backend/migrations_dump.txt
+          #     exit 1
+          #   fi
           command: |
-            if [ $? -eq 0 ] && grep -q "Schema successfully updated" ~/project/backend/migrations_dump.txt; then
+            if [ $? -eq 0 ] && grep -q "Schema successfully updated" ~/project/backend/migrations_results.txt; then
               echo "Migration was successful and schema was updated"
             else
               echo "Migration failed or schema was not updated"
               echo "Reasons:"
-              cat ~/project/backend/migrations_dump.txt
-              # cat migrations_dump.txt
+              cat ~/project/backend/migrations_results.txt
               exit 1
             fi
       - run:
