check migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -260,6 +260,9 @@ jobs:
       - image: cimg/node:13.8.0
     steps:
       - checkout
+      - run:
+          name: Install dependencies
+          command: npm install
       - install_awscli
       - run:
           name: Run migrations
@@ -267,20 +270,24 @@ jobs:
             cd backend
             npm install
             npm run migrations > migrations_dump.txt
+            when: always
+      - run:
+          name: Check migration results
+          command: |
+            if [ $? -eq 0 ] && grep -q "Schema successfully updated" migrations_dump.txt; then
+              echo "Migration was successful and schema was updated"
+            else
+              echo "Migration failed or schema was not updated"
+              echo "Reasons:"
+              cat migrations_results.txt
+              exit 1
+            fi
       - run:
           name: Send migration results to kvdb.io
           command: |
-            # export KVDB_BUKET=$KVDB_BUKET
-            # echo "KVDB_BUKET==$KVDB_BUKET"
-            #   curl -d '1' https://kvdb.io/${KVDB_BUKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            echo ~/project/backend/migrations_dump.txt
-            cat ~/project/backend/migrations_dump.txt
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-              echo "sucess"
-              # echo "${CIRCLE_WORKFLOW_ID:0:7}"
-              # curl -d '1' https://kvdb.io/2xUKChgegBwMqr8mh7caSF/migration_${CIRCLE_WORKFLOW_ID:0:7}
-
+              curl -d '1' https://kvdb.io/2xUKChgegBwMqr8mh7caSF/migration_${CIRCLE_WORKFLOW_ID:0:7}
             fi
       - destroy-environment     
       - revert-migrations
